"""Adapter between routing-facing flood-risk schemas and the simulation engine.

Replace this service's calculations when the calibrated Member 2 model is ready;
the HTTP contract can remain stable.
"""

from fastapi import HTTPException

from app.api.schemas import (
    RoadFloodState,
    ScenarioSimulationRequest,
    ScenarioSimulationResponse,
)
from app.api.simulation import build_simulation
from app.simulation.engine import STATUS_BANDS, Simulation, status_of
from app.simulation.flood_models import DEFAULT_MODEL
from app.network.models import Road


def model_status() -> dict:
    return {
        "implementation_status": "placeholder",
        "model_name": DEFAULT_MODEL,
        "calibrated": False,
        "historical_susceptibility_integrated": False,
        "bucket_threshold_simulation_integrated": True,
        "status_bands": {name: threshold for name, threshold in STATUS_BANDS},
        "notes": (
            "Values are generated by the repository's placeholder bucket model. "
            "They are suitable for routing integration tests, not operational decisions."
        ),
    }


def states_for_simulation(sim: Simulation) -> list[RoadFloodState]:
    frame = sim.frames[-1]
    return [_state_at(sim, road) for road in sim.network.roads]


def _state_at(sim: Simulation, road: Road) -> RoadFloodState:
    frame = sim.frames[-1]
    loading = frame.loading[road.index]
    onset_tick = sim.onset_tick[road.index]
    return RoadFloodState(
        road_id=road.road_id,
        status=status_of(loading),
        loading=loading,
        rainfall_mm_per_h=frame.rainfall_mm_per_h,
        cumulative_rain_mm=round(frame.cumulative_rain_mm, 2),
        observed_at=frame.time,
        time_to_threshold_minutes=(
            onset_tick * sim.step_minutes if onset_tick is not None else None
        ),
    )


def current_state(sim: Simulation, road_id: str) -> RoadFloodState:
    road = sim.network.by_id.get(road_id)
    if road is None:
        raise HTTPException(404, f"unknown road {road_id}")
    return _state_at(sim, road)


def run_scenario(app, body: ScenarioSimulationRequest) -> ScenarioSimulationResponse:
    sim = build_simulation(app, body)
    sim.run()
    states = states_for_simulation(sim)
    return ScenarioSimulationResponse(
        scenario_name=body.scenario_name,
        model_name=sim.model.name,
        rainfall_source=sim.rainfall.source,
        step_minutes=sim.step_minutes,
        started_at=sim.rainfall.start,
        completed_at=sim.frames[-1].time,
        states=states,
    )
